name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, Linux, X64, Docker]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag azure-python:$(date +%s)
    - name: Upload the container to Azure container registry
      run: docker push lottoregistry.azurecr.io/azure-python:$(date +%s)
